# Generated by Django 5.1.2 on 2024-10-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Genre', models.CharField(max_length=60)),
                ('Author', models.CharField(max_length=60)),
                ('Publish_date', models.DateField()),
                ('Number_pages', models.IntegerField()),
                ('Book_cover', models.CharField()),
            ],
        ),
    ]
